version: '2'
services:
  web:
    image: nginx:alpine
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html
     - ./docker/nginx/conf.d:/etc/nginx/conf.d
  php:
    image: php:7.1-fpm-alpine
    volumes:
     - .:/var/www/html
